version: '3'

services:
  zookeeper:
    image: wurstmeister/zookeeper

  kafka:
    image: wurstmeister/kafka
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=localhost
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
    ports:
      - "9092:9092"
    depends_on:
       - zookeeper

  data-generator:
    build:
      context: ./data-kafka-service
      dockerfile: Dockerfile
    environment:
      - KAFKA_CLIENT_CONNECT=kafka:9092
    depends_on:
      - kafka

  casa:
    image: cassandra
    volumes:
      - "./cassandra/cassandra-init.sh:/cassandra-init.sh"
    command: "sh /cassandra-init.sh"

