version: '3'

services:
  zookeeper:
    image: wurstmeister/zookeeper

  kafka:
    image: wurstmeister/kafka
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=localhost
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
    ports:
      - "9092:9092"
    depends_on:
       - zookeeper

  data-generator:
    build:
      context: ./data-kafka-service
      dockerfile: Dockerfile
    network_mode: host
    environment:
      - KAFKA_CLIENT_CONNECT=localhost:9092
    depends_on:
      - kafka